[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."cron-run"]
  schedule = "* * * * *"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
